/** Reproducible before/after artifact, no network and no production writes.
 * Run: npx tsx scripts/editorial/evaluate.ts
 * Frozen public NHL examples are evaluation inputs, never runtime stat sources.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { generatePlayerWriteup, type WriteupPlayer } from '../../packages/shared/src/playerWriteup/index';

const root = resolve(import.meta.dirname, '../..');
const fixtures = JSON.parse(readFileSync(join(root, 'docs/editorial-evaluation/nhl-2025-26-examples.json'), 'utf8')) as Array<WriteupPlayer & { source: string }>;
// Last correctness baseline immediately before this editorial work, portable
// across cherry-picks because the original source commit is retained in git.
const baselineRef = '1365b357';
const oldSource = execFileSync('git', ['show', `${baselineRef}:packages/shared/src/playerWriteup/index.ts`], { cwd: root, encoding: 'utf8' })
  .replace("'../constants/season'", JSON.stringify(join(root, 'packages/shared/src/constants/season.ts')));
const temp = mkdtempSync(join(tmpdir(), 'citrus-editorial-'));
try {
  writeFileSync(join(temp, 'baseline.ts'), oldSource);
  const old = await import(pathToFileURL(join(temp, 'baseline.ts')).href);
  const examples = fixtures.map(player => ({ player: player.name, source: player.source,
    before: old.generatePlayerWriteup(player, { projectionSeason: 2026 }),
    after: generatePlayerWriteup(player, { projectionSeason: 2026 }),
  }));
  const scrub = (value: string) => value.replace(/\d+(?:\.\d+)?/g, '#');
  const metrics = {
    firstFourBeforeDistinctAnalyses: new Set(examples.slice(0, 4).map(e => scrub(e.before.analysis))).size,
    firstFourAfterDistinctAnalyses: new Set(examples.slice(0, 4).map(e => scrub(e.after.analysis))).size,
  };
  if (metrics.firstFourAfterDistinctAnalyses !== 4) throw new Error('Contrasting NHL examples lost analytical differentiation');
  const lines = [
    '# Citrus editorial before/after evaluation', '',
    'Generated by `npx tsx scripts/editorial/evaluate.ts`. Baseline: `1365b357` (season correctness already applied). The examples use public NHL regular-season 2025-26 counting stats retrieved September 12, 2026. These frozen evaluation fixtures are not a competing production stat store. No projections or current player news are invented.', '',
    'The same historical evidence now selects different analytical angles. Similar profiles can still share a mechanism; renaming a player alone deliberately cannot change the assessment.', '',
    `Names/numbers removed: the four forward examples had ${metrics.firstFourBeforeDistinctAnalyses} distinct analysis before and ${metrics.firstFourAfterDistinctAnalyses} after. This checks these fixtures, not universal writing quality.`, '',
    '| Player | Before | After |', '|---|---|---|',
    ...examples.map(e => `| ${e.player} | ${e.before.headline} | ${e.after.headline} |`), '',
  ];
  for (const e of examples) lines.push(`## ${e.player}`, '', `[NHL source](${e.source})`, '', '**Before analysis**', '', e.before.analysis, '', '**After assessment**', '', e.after.summary, '', e.after.analysis, '');
  const p: WriteupPlayer = { id: 1, name: 'Sample Forward', position: 'C', statsSeason: 2025, stats: { gamesPlayed: 80, goals: 30, assists: 50, points: 80, shots: 240, powerPlayPoints: 35 } };
  const now = new Date('2026-09-12T12:00:00Z');
  const news = [{ player_ids: [1], title: 'Sample Forward practiced with the first power-play unit.', snippet: null,
    source_id: 'example', url: 'https://example.com/hockey/practice', published_at: '2026-09-11T18:00:00Z' }];
  const plain = generatePlayerWriteup(p, { now, projectionSeason: 2026 });
  const withNews = generatePlayerWriteup(p, { now, projectionSeason: 2026, newsItems: news });
  lines.push('## Counterfactual news (synthetic, not reporting)', '', 'This deliberately fictional fixture isolates the effect of one qualifying practice report. Its date and source remain separate from historical actuals.', '', '**Without news**', '', plain.analysis, '', '**With confirmed first-unit practice evidence**', '', withNews.summary, '', withNews.analysis, '', 'Production evidence selection also rejects wrong players, undated/future/stale stories, prompt instructions, conditional or retrospective claims, and superseded health reports. Those cases are behavioral tests, not claims about these six players.', '');
  writeFileSync(join(root, 'docs/editorial-evaluation/before-after.md'), lines.join('\n'));
  writeFileSync(join(root, 'docs/editorial-evaluation/results.json'), JSON.stringify({ baselineRef, metrics, examples, counterfactual: { plain, withNews } }, null, 2) + '\n');
  console.log(`Wrote ${examples.length} official-stat examples and one synthetic news counterfactual.`);
} finally { rmSync(temp, { recursive: true, force: true }); }
