CREATE OR REPLACE VIEW public.v_player_game_stat_long WITH (security_invoker=true) AS
SELECT pgs.game_id,
    pgs.player_id,
    pgs.game_date,
    pgs.is_goalie,
    v.stat_key,
    v.value
   FROM player_game_stats pgs
     CROSS JOIN LATERAL ( VALUES ('goals'::text,'skater'::text,COALESCE(pgs.nhl_goals, 0)::numeric), ('assists'::text,'skater'::text,COALESCE(pgs.nhl_assists, 0)::numeric), ('power_play_points'::text,'skater'::text,COALESCE(pgs.nhl_ppp, 0)::numeric), ('short_handed_points'::text,'skater'::text,COALESCE(pgs.nhl_shp, 0)::numeric), ('shots_on_goal'::text,'skater'::text,COALESCE(pgs.nhl_shots_on_goal, 0)::numeric), ('blocks'::text,'skater'::text,COALESCE(pgs.nhl_blocks, 0)::numeric), ('hits'::text,'skater'::text,COALESCE(pgs.nhl_hits, 0)::numeric), ('penalty_minutes'::text,'skater'::text,COALESCE(pgs.nhl_pim, 0)::numeric), ('plus_minus'::text,'skater'::text,COALESCE(pgs.nhl_plus_minus, 0)::numeric), ('power_play_goals'::text,'skater'::text,COALESCE(pgs.nhl_ppg, 0)::numeric), ('power_play_assists'::text,'skater'::text,COALESCE(pgs.nhl_ppa, 0)::numeric), ('short_handed_goals'::text,'skater'::text,COALESCE(pgs.nhl_shg, 0)::numeric), ('short_handed_assists'::text,'skater'::text,COALESCE(pgs.nhl_sha, 0)::numeric), ('game_winning_goals'::text,'skater'::text,COALESCE(pgs.nhl_gwg, 0)::numeric), ('overtime_goals'::text,'skater'::text,COALESCE(pgs.nhl_otg, 0)::numeric), ('faceoff_wins'::text,'skater'::text,COALESCE(pgs.nhl_faceoff_wins, 0)::numeric), ('faceoff_losses'::text,'skater'::text,COALESCE(pgs.nhl_faceoff_losses, 0)::numeric), ('takeaways'::text,'skater'::text,COALESCE(pgs.nhl_takeaways, 0)::numeric), ('giveaways'::text,'skater'::text,COALESCE(pgs.nhl_giveaways, 0)::numeric), ('shot_attempts'::text,'skater'::text,COALESCE(pgs.nhl_shot_attempts, 0)::numeric), ('shots_missed'::text,'skater'::text,COALESCE(pgs.nhl_shots_missed, 0)::numeric), ('shots_blocked_by_opp'::text,'skater'::text,COALESCE(pgs.nhl_shots_blocked, 0)::numeric), ('shifts'::text,'skater'::text,COALESCE(pgs.nhl_shifts, 0)::numeric), ('toi_minutes'::text,'skater'::text,round(COALESCE(pgs.nhl_toi_seconds, 0)::numeric / 60.0, 4)), ('wins'::text,'goalie'::text,COALESCE(pgs.nhl_wins, 0)::numeric), ('saves'::text,'goalie'::text,COALESCE(pgs.nhl_saves, 0)::numeric), ('shutouts'::text,'goalie'::text,COALESCE(pgs.nhl_shutouts, 0)::numeric), ('goals_against'::text,'goalie'::text,COALESCE(pgs.nhl_goals_against, 0)::numeric), ('losses'::text,'goalie'::text,COALESCE(pgs.nhl_losses, 0)::numeric), ('ot_losses'::text,'goalie'::text,COALESCE(pgs.nhl_ot_losses, 0)::numeric), ('shots_faced'::text,'goalie'::text,COALESCE(pgs.nhl_shots_faced, 0)::numeric), ('even_saves'::text,'goalie'::text,COALESCE(pgs.nhl_even_saves, 0)::numeric), ('pp_saves'::text,'goalie'::text,COALESCE(pgs.nhl_pp_saves, 0)::numeric), ('sh_saves'::text,'goalie'::text,COALESCE(pgs.nhl_sh_saves, 0)::numeric), ('goalie_toi_minutes'::text,'goalie'::text,round(COALESCE(pgs.nhl_toi_seconds, 0)::numeric / 60.0, 4))) v(stat_key, applies_to, value)
  WHERE (v.applies_to = 'goalie'::text) = COALESCE(pgs.is_goalie, false);
