import {test} from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {indexed,verifyEarlierOnly,guard,membership,plannedBlocks,verifyInputs,manifestFingerprint} from './review_calibration_stability.mjs';
const row=(game,event,date)=>({game_id:game,event_id:event,game_date:date});
test('strict chronological game-disjoint fit',()=>verifyEarlierOnly([row(1,1,'2022-01-01')],[row(2,1,'2022-02-01')]));
for(const mode of ['same_day','future','same_game','duplicate','invalid_date'])test('reject '+mode,()=>{const fit=[row(1,1,'2022-01-01')],evaluation=[row(2,1,'2022-02-01')];if(mode==='same_day')evaluation[0].game_date='2022-01-01';if(mode==='future')fit[0].game_date='2022-03-01';if(mode==='same_game')evaluation[0].game_id=1;if(mode==='duplicate')fit.push(fit[0]);if(mode==='invalid_date')fit[0].game_date='2022-02-30';assert.throws(()=>verifyEarlierOnly(fit,evaluation));});
test('both losses required',()=>{const x={fixed:{brier:.1,log_loss_clipped:.2},expanding:{brier:.1,log_loss_clipped:.2}};assert(guard(x));x.expanding.brier=.11;assert(!guard(x));x.expanding.brier=NaN;assert.throws(()=>guard(x));});
test('one date per game',()=>assert.throws(()=>indexed([row(1,1,'2022-01-01'),row(1,2,'2022-01-02')])));
function fixture(){const early=Array.from({length:100},(_,i)=>({...row(1+Math.floor(i/2),i,'2022-01-01'),target:i%2})),jan=[{...row(51,1,'2022-01-16'),target:0}],feb=[{...row(52,1,'2022-02-01'),target:1}],records=[...early,...jan,...feb];return {records,blocks:[{month:'2022-01',train:membership(early),test:membership(jan)},{month:'2022-02',train:membership([...early,...jan]),test:membership(feb)}]};}
test('partial first month and full expanding cohort',()=>{const f=fixture(),b=plannedBlocks(f.records,'2022-01-16',f.blocks);assert.equal(b.length,2);assert.equal(b[1].train.length,101);assert.equal(b[0].test.length,1);});
for(const mode of ['missing_month','keyhash','train_count','dropped_event','target_support'])test('reject planned '+mode,()=>{const f=fixture();if(mode==='missing_month')f.blocks.pop();if(mode==='keyhash')f.blocks[0].test.keys_sha256='0'.repeat(64);if(mode==='train_count')f.blocks[1].train.events=100;if(mode==='dropped_event')f.records.pop();if(mode==='target_support')f.records.forEach(r=>r.target=0);assert.throws(()=>plannedBlocks(f.records,'2022-01-16',f.blocks));});
test('membership digest insensitive to input order',()=>{const f=fixture();assert.deepEqual(membership(f.records),membership([...f.records].reverse()));});
test('test request excludes outcomes while training labels match',()=>{const expected=[{...row(1,1,'2022-01-01'),target:1}],train=[{...expected[0],raw_probability:.1,context:{prior_sog_same_team:null}}],{target,...request}=train[0];verifyInputs(train,expected,true);verifyInputs([request],expected,false);assert.throws(()=>verifyInputs(train,expected,false));train[0].target=0;assert.throws(()=>verifyInputs(train,expected,true));});
test('request population and numeric validity',()=>{const expected=[{...row(1,1,'2022-01-01'),target:1}],request={...expected[0],raw_probability:NaN,context:{}};assert.throws(()=>verifyInputs([request],expected,true));request.raw_probability=.1;request.event_id=2;assert.throws(()=>verifyInputs([request],expected,true));});
test('manifest fingerprint recursively canonicalizes exact compact ASCII structure',()=>{const m={inventories:{z:['b','a'],a:[]},checked:{z:'last',a:'first'}};const raw='{"checked":{"a":"first","z":"last"},"inventories":{"a":[],"z":["b","a"]}}';assert.equal(manifestFingerprint(m),crypto.createHash('sha256').update(raw).digest('hex'));assert.notEqual(manifestFingerprint(m),manifestFingerprint({...m,checked:{...m.checked,a:'changed'}}));assert.throws(()=>manifestFingerprint({bad:1.2}));assert.throws(()=>manifestFingerprint({bad:'é'}));});
