import test from 'node:test';
import assert from 'node:assert/strict';
import {scalarPrediction,band,guard,preserveInputs,verifyPredictions,trainVocabulary} from './review_timing_candidate.mjs';
const context=()=>({shot_type:'wrist',prior_sog_same_team:'1',strength:'5v5'});
const model=()=>({contract:'citrus-timing-conditional-calibration-v1',publishable:false,timing_ridge:100,timing_categories:['same_clock','up_to_1s'],timing_offsets:[.5,-.5],settings:{epsilon:1e-6,reference_probability:.1,knots:[.000001,.1,.999999]},states:['1'],shared_slopes:[1,1],context_slopes:[[1,1]],intercept:Math.log(.1/.9),vocabulary:{shot_type:['wrist'],prior_sog_same_team:['1'],strength:['5v5']},offsets:[0,0,0]});
test('timing scalar at reference',()=>{assert(Math.abs(scalarPrediction(model(),.1,context(),0)-1/(1+Math.exp(-(Math.log(.1/.9)+.5))))<1e-15);});
test('timing applies before final clipping',()=>{const m=model();m.shared_slopes=[0,0];m.context_slopes=[[0,0]];m.intercept=40;m.timing_offsets[0]=-40;assert.equal(scalarPrediction(m,.1,context(),0),.5);});
test('unknown category and overten reference have zero offset',()=>{assert.equal(scalarPrediction(model(),.1,context(),2),scalarPrediction(model(),.1,context(),11));});
test('unknown state receives shared slopes and no timing',()=>{const c={...context(),prior_sog_same_team:null};assert(Math.abs(scalarPrediction(model(),.1,c,null)-.1)<1e-15);});
for(const [gap,expected]of [[0,'same_clock'],[1,'up_to_1s'],[2,'over_1_under_3s'],[3,'from_3_to_10s'],[10,'from_3_to_10s'],[11,null]])test(`fixedband${gap}`,()=>assert.equal(band('1',gap),expected));
for(const gap of [null,true,-1,NaN,Infinity,'1'])test(`bad stateone gap ${String(gap)}`,()=>assert.throws(()=>band('1',gap)));
test('first category duplicate and nonfinite parameters rejected',()=>{const m=model();m.timing_categories=['same_clock','same_clock'];assert.throws(()=>scalarPrediction(m,.1,context(),0));m.timing_categories=['same_clock','up_to_1s'];m.timing_offsets[0]=NaN;assert.throws(()=>scalarPrediction(m,.1,context(),0));});
const source=()=>({game_id:2023020001,event_id:1,game_date:'2023-10-01',raw_probability:.1,context:context(),target:0,groups:Object.fromEntries(['shot_type','strength','season','game_type','previous_event_type','prior_sog_same_team','rink_home_id','defending_empty_net'].map(n=>[n,null]))});
function fixture(){const s=source(),k=JSON.stringify([s.game_id,s.event_id]),t=new Map([[k,{target:0,month:'2023-10',state:'1',gap_seconds:1,gap_band:'up_to_1s'}]]);const input={game_id:s.game_id,event_id:s.event_id,game_date:s.game_date,raw_probability:s.raw_probability,context:s.context,gap_seconds:1,gap_band:'up_to_1s'};return {s,k,t,input};}
test('exact target-free source input',()=>{const {s,t,input}=fixture();preserveInputs([input],[s],false,t);});
for(const change of ['target','raw','gap','context','missing'])test(`reject input ${change}`,()=>{const {s,t,input}=fixture();if(change==='target')input.target=0;if(change==='raw')input.raw_probability=.2;if(change==='gap')input.gap_seconds=2;if(change==='context')input.context={...context(),strength:null};assert.throws(()=>preserveInputs(change==='missing'?[]:[input],[s],false,t));});
test('train vocabulary excludes unobserved timings',()=>{const {input}=fixture(),m=model();m.timing_categories=['up_to_1s'];m.timing_offsets=[.3];trainVocabulary(m,[input]);m.timing_categories=['same_clock','up_to_1s'];assert.throws(()=>trainVocabulary(m,[input]));});
function predictions(){const {s,k}=fixture(),m=model(),expected={...s,gap_seconds:1},old={game_id:s.game_id,event_id:s.event_id,target:0,groups:s.groups,predictions:{fixed:.1,expanding:.12}},r={...old,predictions:{...old.predictions,timing:scalarPrediction(m,.1,context(),1)}};return {m,expected,old,r,frozen:new Map([[k,old]])};}
test('scalar and exactcontrols allsameevents',()=>{const {m,expected,r,frozen}=predictions();assert.equal(verifyPredictions([r],[expected],m,frozen),0);});
for(const change of ['control','timing','group','duplicate','target','nonfinite'])test(`reject predictions ${change}`,()=>{const {m,expected,r,frozen}=predictions();if(change==='control')r.predictions.fixed=.11;if(change==='timing')r.predictions.timing+=.01;if(change==='group')r.groups={};if(change==='target')r.target=1;if(change==='nonfinite')r.predictions.timing=NaN;assert.throws(()=>verifyPredictions(change==='duplicate'?[r,r]:[r],[expected],m,frozen));});
test('bothloss guard no compensation',()=>{const v={timing:{brier:.1,log_loss_clipped:.2},expanding:{brier:.1,log_loss_clipped:.2}};assert(guard(v));v.timing.brier=.11;v.timing.log_loss_clipped=.1;assert(!guard(v));v.timing.brier=Infinity;assert.throws(()=>guard(v));});
