import {test} from 'node:test';
import assert from 'node:assert/strict';
import {aggregate,band,verifyPoints,verifyDeclaration} from './review_forward_shooter_decomposition.mjs';
const metrics=['brier','log_loss_clipped'],components=['total','map_pipeline','global','shooter_increment'];
function fixture(){
  const rows=[0,1,0,1].map((target,i)=>({game_id:1+Math.floor(i/2),event_id:i,target,groups:{prior_sog_same_team:i%2?'true':null},predictions:{frozen_conditional_shape:.1,new_neutral:.2,global_control:.15,shooter:.12}}));
  const records=rows.map(r=>({game_id:r.game_id,event_id:r.event_id,target:r.target,probability:.2,game_date:r.game_id===1?'2022-01-01':'2022-02-01'}));return {rows,records};
}
function report(g){const n=g.overall.get('null').events;const entry=e=>({events:e.events,games:e.games.size,support:'sparse',metrics:Object.fromEntries(metrics.map((m,i)=>[m,Object.fromEntries(components.map((c,j)=>[c,{mean_delta:e.sums[i][j]/e.events,weighted_contribution:e.sums[i][j]/n}]))]))});return {events:n,games:g.overall.get('null').games.size,observed_cells:g.cells.size,overall:entry(g.overall.get('null')),cells:[...g.cells.values()].map(e=>({cell:e.value,...entry(e)})),rollups:Object.fromEntries(['anchor_band','month','prior_sog_same_team'].map(k=>[k,[...g[k].values()].map(e=>({value:e.value,...entry(e)}))]))};}
test('all right-anchored edges',()=>{[0,.01,.025,.05,.1,.2,.35,.5,.75,1].forEach((p,i)=>assert.equal(band(p),Math.min(i,8)));for(const p of [null,NaN,-.1,1.1])assert.throws(()=>band(p));});
test('manual four component Brier and log loss arithmetic',()=>{const f=fixture(),g=aggregate(f.rows.slice(0,1),f.records.slice(0,1)),s=g.overall.get('null').sums;const b=[.12**2-.1**2,.2**2-.1**2,.15**2-.2**2,.12**2-.15**2];b.forEach((x,i)=>assert(Math.abs(s[0][i]-x)<1e-15));assert(Math.abs(s[1][0]-Math.log(.9/.88))<1e-15);verifyPoints(g,report(g));});
test('permutation, months and explicit null states retained',()=>{const f=fixture(),g=aggregate(f.rows,f.records);assert.equal(g.month.size,2);assert(g.prior_sog_same_team.has('null'));verifyPoints(aggregate([...f.rows].reverse(),[...f.records].reverse()),report(g));});
for(const mode of ['duplicate','missing','target','date','same_game_date','probability','output','unknown_state'])test('reject source '+mode,()=>{const f=fixture();if(mode==='duplicate')f.rows.push(f.rows[0]);if(mode==='missing')f.records.pop();if(mode==='target')f.records[0].target=1;if(mode==='date')f.records[0].game_date='2022-02-30';if(mode==='same_game_date')f.records[0].game_date='2022-01-02';if(mode==='probability')f.records[0].probability=.3;if(mode==='output')delete f.rows[0].predictions.shooter;if(mode==='unknown_state')delete f.rows[0].groups.prior_sog_same_team;assert.throws(()=>aggregate(f.rows,f.records));});
for(const mode of ['point','weighted','cell','month','support'])test('reject report '+mode,()=>{const f=fixture(),g=aggregate(f.rows,f.records),r=report(g);if(mode==='point')r.overall.metrics.brier.total.mean_delta+=.01;if(mode==='weighted')r.cells[0].metrics.brier.global.weighted_contribution+=.01;if(mode==='cell')r.cells[0].cell[2]='invented';if(mode==='month')r.rollups.month.pop();if(mode==='support')r.overall.support='supported_exploratory';assert.throws(()=>verifyPoints(g,r));});
function declaration(){return {analysis:'adaptive-development-no-fit-forward-shooter-loss-decomposition',publishable:false,fit_permitted:false,anchor:'frozen_conditional_shape',edges:[0,.01,.025,.05,.1,.2,.35,.5,.75,1],components,models:['frozen_conditional_shape','new_neutral','global_control','shooter'],cell_axes:['anchor_probability_band_index','month','prior_sog_same_team'],epsilon:1e-12,pins:{'official-forward-shooter-movement-20260906-retry1':'829119131d856969b5278d1b14d1a711c19b4a5a404b6b932ee40cf29af9fe22','forward-shooter-movement-review-20260906-retry1':'93e9d10c339f3b53e683f992abfaa7d2d85b534fe8d834f6e74178e2b10b8b2d'},plan_path:'docs/analytics-forward-shooter-decomposition-plan-20260906.md',plan_sha256:'aa79a619e76647de8c9496d89a8ac9517792f9d93e623130e28ff17bac133540',bootstrap:{draws:256,seed:60906,unit:'whole_game',interval:'percentile_95',contribution_denominator:'full_resampled_fold_events',cell_mean_empty_draws:'excluded_and_counted'},support_label:{sparse_below_events:100,sparse_below_games:30,all_observed_cells_retained:true},code_sha256:Object.fromEntries(['decompose_forward_shooter.py','test_decompose_forward_shooter.py','test_decompose_forward_shooter_review.py'].map(n=>['scripts/proof/'+n,'0'.repeat(64)]))};}
test('exact no-fit declaration',()=>verifyDeclaration(declaration()));
for(const mode of ['fit','publish','models','components','bootstrap','plan','pin','support','code'])test('reject declaration '+mode,()=>{const d=declaration();if(mode==='fit')d.fit_permitted=true;if(mode==='publish')d.publishable=true;if(mode==='models')d.models.reverse();if(mode==='components')d.components=[...components].reverse();if(mode==='bootstrap')d.bootstrap.seed=1;if(mode==='plan')d.plan_sha256='0'.repeat(64);if(mode==='pin')d.pins.extra='0'.repeat(64);if(mode==='support')d.support_label.sparse_below_events=99;if(mode==='code')d.code_sha256={};assert.throws(()=>verifyDeclaration(d));});
