// Phase 4.5 chunk 11g.5a — client-side state machine types.
//
// The state machine is split into:
//   - `DraftClientState` — discriminated union of every state the
//     client can be in.
//   - `DraftClientEvent` — discriminated union of every event the
//     state machine reacts to (network events, timer fires,
//     server messages, caller actions).
//   - `SideEffect` — discriminated union of every side effect the
//     pure `reduce` function can request the runner to execute
//     (open WS, fetch token, schedule timer, send message, etc.).
//
// The split keeps `reduce` pure (and trivially unit-testable) and
// localizes all I/O to the runner layer.
//
// `DraftClientCallbacks` is the integration surface for chunk 11g.5b
// (UX layer): the runner invokes these callbacks as state evolves
// so the React layer can subscribe without coupling to the state
// machine internals.

import type {
  BufferedDraftEvent,
  DraftClientMessage,
  DraftServerMessage,
  DraftSnapshot,
} from '@citrus/shared';

// ── State ──────────────────────────────────────────────────────────

/**
 * Client-side WebSocket lifecycle state. Every state the client can
 * be in is represented exactly once. Transitions are driven by
 * `DraftClientEvent`s through the pure `reduce` function.
 *
 * The state machine is intentionally explicit — no implicit
 * "connecting to maybe-dead WS" or "reconnecting forever" zombies.
 * Every state has well-defined entry / exit conditions documented
 * inline.
 */
export type DraftClientState =
  | {
      /** No connection attempted. Initial state; entered via `disconnect_requested`. */
      kind: 'idle';
    }
  | {
      /**
       * Fetching a draft token from the discovery endpoint
       * (`GET /api/drafts/:draftId/server`). Re-entered on every
       * reconnect attempt so token freshness + league-membership
       * authorization are re-validated on each connection — the
       * "reconnect doubles as re-authorization" pattern (industry-
       * standard for short-lived bearer tokens).
       */
      kind: 'fetching_token';
      attempt: number;
    }
  | {
      /**
       * WebSocket handshake in progress (browser is sending the
       * upgrade request). Token has been fetched; URL has been
       * computed; ws.onopen has not yet fired.
       */
      kind: 'connecting';
      wsUrl: string;
      attempt: number;
    }
  | {
      /**
       * Happy path: WebSocket is open and the server has confirmed
       * the connection. `lastSeenSeq` advances on every `event`
       * server message; used as the cursor for resync requests on
       * reconnect.
       *
       * `sessionId` is a per-connection UUID generated by the
       * runner when the WS opens; included in resync requests for
       * server-side correlation tracing.
       */
      kind: 'connected';
      wsUrl: string;
      lastSeenSeq: number;
      sessionId: string;
    }
  | {
      /**
       * A fresh WebSocket has opened after a disconnect; the client
       * has issued `{type: 'resync', payload: {sinceSeq: N}}` and is
       * awaiting the response. Two outcomes:
       *   - `resync_response_received` with `ok: true` → `connected`
       *     (events delivered to caller via `onEvents` callback)
       *   - `resync_response_received` with `ok: false` (too_old)
       *     → `snapshot_required` (server's ring buffer evicted past
       *     the client's cursor — full snapshot resync needed)
       */
      kind: 'resyncing';
      wsUrl: string;
      sinceSeq: number;
      sessionId: string;
    }
  | {
      /**
       * Server returned `too_old` from the resync request. The
       * runner must fetch a full snapshot via the HTTP endpoint
       * (chunk 11g.7's followup — currently throws `not_implemented`).
       * On `snapshot_fetched`, transitions to `connected` with
       * state replaced from the snapshot. On `snapshot_fetch_failed`,
       * transitions to `reconnecting`.
       */
      kind: 'snapshot_required';
      wsUrl: string;
      sessionId: string;
    }
  | {
      /**
       * Disconnected; waiting for the exponential-backoff timer to
       * fire so the runner can attempt a fresh `fetching_token →
       * connecting` cycle. `nextAttemptAt` is a wall-clock ms
       * timestamp so the UX layer (chunk 11g.5b) can render a
       * countdown ("retrying in 4s...").
       */
      kind: 'reconnecting';
      nextAttemptAt: number;
      attempt: number;
      lastError: string | null;
    }
  | {
      /**
       * Terminal state. No more retries. Triggered by:
       *   - `auth_failure`: 401/403 from token discovery, or
       *     close codes 4001-4099 from the WS handshake (token
       *     verification failed server-side). Also close code 4300
       *     (chunk 11g.10 sub-step 10c-2 gate (a) — non-UUIDv4 sub,
       *     "bad shape" that can't be fixed by retrying the same
       *     token; only remediation is fresh auth).
       *   - `invalid_lobby`: lobby not found, draft completed, or
       *     close codes 4100-4199.
       *   - `permanent_server_error`: close code 4200+ or any
       *     close code the server explicitly marked permanent.
       *   - `draft_not_initialized`: close code 4400 (chunk 11g.10
       *     sub-step 10c-2 gate (b) — commissioner hasn't configured
       *     the draft yet). Distinct from server error: banner reads
       *     "This draft hasn't been set up yet"; UX offers a manual
       *     RETRY NOW affordance for the "commissioner just finished"
       *     case, but no auto-reconnect fires.
       *
       * The UX layer presents an error UI; user must take an
       * action (re-login, return to dashboard, or RETRY NOW for
       * `draft_not_initialized`) to recover.
       */
      kind: 'fatal';
      reason:
        | 'auth_failure'
        | 'invalid_lobby'
        | 'permanent_server_error'
        | 'draft_not_initialized';
      errorMessage: string;
    };

// ── Events ─────────────────────────────────────────────────────────

/**
 * Every event the state machine reacts to. Categories:
 *   - Caller-initiated: `connect_requested`, `disconnect_requested`
 *   - Token fetch outcomes: `token_fetched`, `token_fetch_failed`
 *   - WebSocket lifecycle: `ws_opened`, `ws_message`, `ws_closed`,
 *     `ws_error`
 *   - Resync flow: `resync_response_received`, `snapshot_fetched`,
 *     `snapshot_fetch_failed`
 *   - Timers: `backoff_timer_fired`
 *   - Browser environment: `visibility_changed`, `network_changed`
 */
export type DraftClientEvent =
  | { type: 'connect_requested' }
  | { type: 'disconnect_requested' }
  | { type: 'token_fetched'; token: string; wsUrl: string }
  | { type: 'token_fetch_failed'; error: string; statusCode?: number }
  | { type: 'ws_opened'; sessionId: string }
  | { type: 'ws_message'; message: DraftServerMessage }
  | { type: 'ws_closed'; code: number; reason: string }
  | { type: 'ws_error'; error: string }
  | { type: 'snapshot_fetched'; snapshot: DraftSnapshot }
  | { type: 'snapshot_fetch_failed'; error: string }
  | { type: 'backoff_timer_fired' }
  | { type: 'visibility_changed'; isVisible: boolean }
  | { type: 'network_changed'; isOnline: boolean };

// ── Side effects ───────────────────────────────────────────────────

/**
 * Every side effect the pure `reduce` function can request. The
 * runner consumes these in order and executes the I/O. Keeping
 * effects as plain data (not closures) means `reduce` is trivially
 * testable — tests assert on the returned effect descriptors
 * instead of mocking out a whole I/O layer.
 */
export type SideEffect =
  | {
      kind: 'fetch_token';
      /** Discovery endpoint reads draftId from the path. */
      draftId: string;
    }
  | {
      kind: 'open_websocket';
      url: string;
      /** Subprotocol is the JWT itself per chunk 11g.2 step 2. */
      subprotocol: string;
    }
  | {
      kind: 'close_websocket';
      /** Optional code per RFC 6455. Defaults to 1000 normal closure. */
      code?: number;
      reason?: string;
    }
  | {
      kind: 'send_message';
      message: DraftClientMessage;
    }
  | {
      kind: 'schedule_backoff_timer';
      delayMs: number;
    }
  | {
      kind: 'cancel_backoff_timer';
    }
  | {
      kind: 'fetch_snapshot';
      /**
       * The HTTP snapshot endpoint for the chunk-11g.4 in-memory
       * `DraftSnapshot` shape doesn't exist yet (tracked as a
       * Decision Log followup). The runner's handler currently
       * dispatches `snapshot_fetch_failed` immediately so the
       * state machine routes through `reconnecting` cleanly.
       */
      leagueId: string;
    }
  | {
      kind: 'deliver_events';
      /**
       * Hand the caller (chunk 11g.5b UX layer) the events that
       * arrived between disconnect and reconnect, in seq order.
       * The state machine doesn't store these — the UX layer is
       * the consumer.
       */
      events: ReadonlyArray<BufferedDraftEvent>;
    }
  | {
      kind: 'deliver_snapshot';
      snapshot: DraftSnapshot;
    }
  | {
      kind: 'deliver_event';
      /** Single live event from the WS stream. */
      event: BufferedDraftEvent;
    }
  | {
      kind: 'deliver_presence';
      payload: {
        kind: 'joined' | 'left';
        userId: string;
        presentUserIds: ReadonlyArray<string>;
      };
    }
  | {
      kind: 'deliver_error';
      payload: { code: string; message: string };
    };

// ── Reduce result ──────────────────────────────────────────────────

export interface ReduceResult {
  state: DraftClientState;
  sideEffects: ReadonlyArray<SideEffect>;
}

// ── Runner integration surface (forward-compat for 5b) ─────────────

/**
 * Callbacks the runner invokes as the state machine evolves.
 * Chunk 11g.5b's UX layer subscribes via these to render banners,
 * apply optimistic state, etc. Names match the matching
 * `deliver_*` side effects so the call sites are self-documenting.
 *
 * The state-change callback fires on every transition; the UX
 * layer uses it to drive banner / status indicator UI.
 */
export interface DraftClientCallbacks {
  onStateChange?: (state: DraftClientState) => void;
  onEvent?: (event: BufferedDraftEvent) => void;
  onEvents?: (events: ReadonlyArray<BufferedDraftEvent>) => void;
  onSnapshot?: (snapshot: DraftSnapshot) => void;
  onPresence?: (payload: {
    kind: 'joined' | 'left';
    userId: string;
    presentUserIds: ReadonlyArray<string>;
  }) => void;
  onError?: (payload: { code: string; message: string }) => void;
}
