import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>readFileSync(p,'utf8');
const db=new PGlite();
await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon;
CREATE TABLE leagues(id uuid primary key,scoring_settings jsonb,settings jsonb);
CREATE TABLE stat_catalog(stat_key text,applies_to text,default_multiplier numeric);
CREATE TABLE league_scoring_rules(league_id uuid,stat_key text,multiplier numeric,updated_at timestamptz,unique(league_id,stat_key));
CREATE TABLE matchups(id uuid primary key,league_id uuid,team1_id uuid,team2_id uuid,week_start_date date,week_end_date date,team1_score numeric,team2_score numeric,updated_at timestamptz,status text);
CREATE TABLE fantasy_matchup_lines(matchup_id uuid,team_id uuid,total_points numeric);
CREATE TABLE calls(kind text,id uuid);
CREATE FUNCTION calculate_matchup_total_score(uuid,uuid,date,date) RETURNS numeric LANGUAGE sql AS $$ SELECT 2*multiplier FROM league_scoring_rules r JOIN matchups m ON m.league_id=r.league_id WHERE m.id=$1 AND stat_key='goals' $$;
CREATE FUNCTION calculate_h2h_category_matchup(uuid,uuid,uuid,uuid,date,date,text[]) RETURNS TABLE(winner text) LANGUAGE sql AS $$ SELECT unnest(ARRAY['team1','tie']) $$;
CREATE FUNCTION persist_matchup_lines(uuid) RETURNS void LANGUAGE plpgsql AS $$ BEGIN INSERT INTO calls VALUES('persist',$1); DELETE FROM fantasy_matchup_lines WHERE matchup_id=$1; INSERT INTO fantasy_matchup_lines SELECT id,team1_id,team1_score FROM matchups WHERE id=$1; INSERT INTO fantasy_matchup_lines SELECT id,team2_id,team2_score FROM matchups WHERE id=$1 AND team2_id IS NOT NULL; END $$;
INSERT INTO stat_catalog VALUES('goals','skater',3),('assists','skater',2);
INSERT INTO leagues SELECT md5(i::text)::uuid,CASE i WHEN 1 THEN NULL WHEN 2 THEN '{"skater":{"goals":0}}'::jsonb WHEN 3 THEN '{"skater":{"goals":-2}}'::jsonb ELSE '{}'::jsonb END,CASE i WHEN 4 THEN '{"scoringFormat":"h2h-categories","categories":["goals","assists"]}'::jsonb ELSE '{}'::jsonb END FROM generate_series(1,5)i;
INSERT INTO league_scoring_rules SELECT id,stat_key,CASE WHEN id=md5('5')::uuid THEN 0 ELSE 99 END,now() FROM leagues CROSS JOIN stat_catalog;
INSERT INTO matchups SELECT md5(('m'||i)::text)::uuid,md5(i::text)::uuid,md5(('t'||i)::text)::uuid,md5(('o'||i)::text)::uuid,current_date-7,current_date-1,99,99,now(),'completed' FROM generate_series(1,5)i;
INSERT INTO matchups SELECT md5('future')::uuid,md5('1')::uuid,md5('t1')::uuid,NULL,current_date+7,current_date+14,99,99,now(),'scheduled';`);
await db.exec(read('supabase/migrations/20260905233000_matchup_scores_follow_scoring_format.sql'));
await db.exec(read('supabase/migrations/20251220000002_create_matchup_calibration_function.sql'));
// Install the original trigger shape, then apply the actual migration after capture.
await db.exec(`CREATE FUNCTION sync_scoring_settings_to_rules() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$; CREATE TRIGGER sync_rules AFTER UPDATE OF scoring_settings ON leagues FOR EACH ROW EXECUTE FUNCTION sync_scoring_settings_to_rules();`);
const capture=read('scripts/release/scoring-rescore/capture.sql');
const migration=read('supabase/migrations/20260912073440_scoring_rules_replace_removed_keys.sql');
const rescore=read('scripts/release/scoring-rescore/rescore.sql');
await db.exec('BEGIN');await db.exec(capture);await db.exec(migration);await db.exec(rescore);
assert.equal((await db.query('SELECT * FROM scoring_rescore_affected')).rows.length,4);
assert.equal((await db.query('SELECT * FROM calls')).rows.length,4);
const rows=(await db.query('SELECT team1_score FROM matchups ORDER BY team1_score')).rows.map(x=>Number(x.team1_score));
assert.deepEqual(rows,[-4,0,1.5,6,99,99]);
await db.exec('ROLLBACK');
assert.equal((await db.query('SELECT * FROM matchups WHERE team1_score<>99')).rows.length,0);
await db.exec('BEGIN');await db.exec(capture);await db.exec(migration);await db.exec(`UPDATE leagues SET settings='{"changed":true}' WHERE id=md5('1')::uuid`);
await assert.rejects(db.exec(rescore),/fingerprint changed/);await db.exec('ROLLBACK');
await db.exec('BEGIN');await db.exec(capture);await db.exec(migration);await db.exec(`CREATE OR REPLACE FUNCTION calculate_matchup_total_score(uuid,uuid,date,date) RETURNS numeric LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture failure'; END $$;`);
await assert.rejects(db.exec(rescore),/Score RPC failed/);await db.exec('ROLLBACK');
console.log('PASS affected-only, unchanged/future exclusion, null/default, missing-key zero, zero/negative, categories, rollback, CAS failure, RPC false failure');
await db.close();
