"""Authored opportunity notes, never generated by substituting player statistics."""
import json
from pathlib import Path

LIBRARY = Path(__file__).with_name('board-reads.json')


def load_board_reads(players, canonical_revision=None, path=LIBRARY, *, deployment_path=None):
    bundle = json.loads(Path(path).read_text())
    from deployment import verify_editorial_review
    verify_editorial_review(bundle, deployment_path) if deployment_path else verify_editorial_review(bundle)
    if canonical_revision and canonical_revision != bundle['canonicalRevision']:
        raise ValueError('Board reads require review against the new canonical snapshot')
    by_id = {str(p['playerId']): p for p in players}
    notes = {}
    for note in bundle['items']:
        pid = note['playerId']
        if pid in notes:
            raise ValueError(f'Duplicate board read: {pid}')
        player = by_id.get(pid)
        if player is None:
            continue
        # Fail rather than silently carrying a team/opportunity claim into a
        # different snapshot. These are existing projections, not assignments.
        for field in ('name', 'team', 'line', 'powerPlay'):
            if player.get(field) != note[field]:
                raise ValueError(f'Board read requires editorial review: {pid} {field}')
        if not note['body'].strip() or len(note['body'].split()) > 60 or '\u2014' in note['body']:
            raise ValueError(f'Invalid board read copy: {pid}')
        if note.get('url') and not note['url'].startswith('https://'):
            raise ValueError(f'Invalid board read source: {pid}')
        notes[pid] = note
    return notes


# An editorial shortlist, not a page-fill quota. Every selection has a specific
# reader decision; having a researched paragraph does not itself earn a feature.
# Roles remain canonical projected scenarios, never confirmed assignments.
FEATURES = {
    '8479318': ('THE FINISHING REBOUND', 'Matthews: career-low conversion alongside sustained shot volume creates a rebound case, not a guarantee of his old scoring peak.', None),
    '8483457': ('WHAT YOUR BLUE LINE STILL NEEDS', 'Hutson: an assist-led first-unit forecast can duplicate a roster strength while leaving a shooting gap.', None),
    '8478178': ('AFTER A CAREER YEAR', 'Raddysh: a 22-goal season with 10 power-play goals raises a repeatability question as Toronto changes the surrounding puck distribution.', None),
    '8478444': ('A REBOUND WITH SOMETHING TO WATCH', 'Boeser: the reported late-season improvement with Rossi supplies a specific camp connection to investigate.', None),
    '8484387': ('THE REBOUND HAS TWO SIDES', 'Michkov: late-season scoring and playoff struggles provide different evidence for a rebound, with deployment still unsettled.', None),
    '8482679': ('BREAKOUT OPPORTUNITY', 'Coronato: first-line/PP1 access puts conversion of opportunity, not a promotion, at the centre of the breakout bet.', None),
    '8482745': ('SECOND LINE, FIRST UNIT', 'McTavish: the power-play assignment changes the interpretation of his second-line role in St. Louis.', None),
    '8484145': ('THE MISSING PROMOTION', 'Benson: first-line access and first-unit access are different; PP2 is the limit to investigate.', None),
    '8481617': ('LINEMATES ARE NOT THE WHOLE JOB', 'Podkolzin: Edmonton top-group access does not include its premium power-play assignment.', None),
    '8475798': ('LATE-BOARD POWER PLAY', 'Granlund: a projected first-unit role offers an offensive route despite a second-line centre assignment.', None),
    '8481519': ('STARTS VS. WIN SUPPORT', 'Knight: compare the chance to play with stronger-team tandems instead of valuing all starts equally.', None),
    '8478406': ('THE TANDEM TRADEOFF', 'Blackwood: Colorado win support does not remove Wedgewood from the allocation of starts.', None),
    '8482157': ('YOUR SCORING CHANGES THE PICK', 'Cuylle: rewarded hits can lift the rank without a top offensive assignment.', 'hits'),
    '8476460': ('BEFORE YOU STACK TEAMMATES', 'Scheifele: shared first-line/PP1 exposure with Connor and Vilardi creates a concentration decision for the fantasy roster.', None),
    '8482109': ('BUILDING AFTER PANARIN', 'Lafreniere: late-season production alongside Zibanejad provides a partnership to follow as Dorofeyev joins the attack.', None),
    '8482122': ('HUGHES HELPS AT EVEN STRENGTH TOO', 'Faber: his production after Hughes arrived adds an offensive case beyond the first-unit debate.', None),
    '8475172': ('A DIFFERENT ROUTE TO COLORADO', 'Kadri: projected PP1 work offers access to MacKinnon and Makar without taking the first-line centre job.', None),
}


def select_board_features(players, notes, weights):
    """Select editorial subjects across the whole board BEFORE pagination.

    Neither rank, row index, page size nor paragraph availability is a reason.
    A category-dependent feature requires a material positive contribution.
    This threshold checks relevance; it never alters projections or rankings.
    """
    selected={}
    for p in players:
        pid=str(p['playerId'])
        if pid not in FEATURES:continue
        label,reason,category=FEATURES[pid]
        contribution=None
        if category:
            from customer_data import raw_totals
            totals=raw_totals(p);configured=weights.get('skater',{})
            weight=configured.get(category,0);value=totals.get(category)
            if weight<=0 or value is None:continue
            contribution=value*weight
            positive=sum(v*configured.get(k,0) for k,v in totals.items()
                         if v is not None and configured.get(k,0)>0)
            if positive<=0 or contribution/positive<.15:continue
        if pid not in notes:
            raise ValueError('Selected editorial feature needs an authored read: '+pid)
        selected[pid]=dict(label=label,reason=reason,category=category,
                           categoryContribution=contribution)
    return selected
