const test=require('node:test');const assert=require('node:assert/strict');
const {comparisonRows}=require('./draft_desk.cjs');
const {readFileSync}=require('node:fs');const {JSDOM}=require('jsdom');
test('offline comparison retains raw totals, respects negative weights and never conflates goalie/skater categories',()=>{
 const players=[{goalie:true,totals:{goals_against:100,saves:1500}},{goalie:true,totals:{goals_against:120,saves:1500}},{goalie:false,totals:{goals:0}}];
 const weights={goalie:{goals_against:-3,saves:.5},skater:{goals:6}};
 const raw=comparisonRows(players,weights,false),impact=comparisonRows(players,weights,true);
 assert.deepEqual(raw.find(r=>r.key==='goals_against').values,[100,120,null]);
 assert.deepEqual(impact.find(r=>r.key==='goals_against').values,[-300,-360,null]);
 assert.deepEqual(impact.find(r=>r.key==='goals_against').edges,[true,false,false]);
 assert.deepEqual(impact.find(r=>r.key==='saves').edges,[false,false,false]);
 assert.deepEqual(raw.find(r=>r.key==='goals').values,[null,null,0]);
 assert.deepEqual(impact.find(r=>r.key==='hits').values,[null,null,null]);
});
test('offline compare controls enforce ten players, follow manual pick state and never alter progress',()=>{
 const kit={fingerprint:'test',revision:'test',league:'Test',projectionDate:'2026-09-19',weights:{skater:{goals:2,assists:1,shots_on_goal:.1},goalie:{}},players:Array.from({length:11},(_,i)=>({key:'canonical:'+(i+1),name:'Test Player '+i,team:'ABC',position:'C',rank:i+1,points:20,games:10,goalie:false,totals:{goals:10+i,assists:20+i,shots_on_goal:100+i}}))};
 const template=readFileSync(__dirname+'/draft_desk.html','utf8').replace('__KIT_DATA__',JSON.stringify(kit)).replace('__DESK_SCRIPT__','');
 const dom=new JSDOM(template,{url:'https://offline.example',runScripts:'outside-only'}),w=dom.window;
 w.eval(readFileSync(__dirname+'/../../packages/shared/src/draftCompare/charts.js','utf8'));
 w.eval(readFileSync(__dirname+'/draft_desk.cjs','utf8'));
 const click=label=>w.document.querySelector('[aria-label="'+label+'"]').click();
 for(let i=0;i<10;i++)click('Compare Test Player '+i);
 assert.equal(w.document.querySelector('#compare-search').disabled,true);
 assert.match(w.document.querySelector('#compare-status').textContent,/Ten players/);
 assert.equal(w.localStorage.length,0);
 const colour=w.document.querySelectorAll('#compare-table thead th')[3].style.borderTop;
 click('Remove Test Player 1 from comparison');click('Compare Test Player 10');
 assert.equal(w.document.querySelectorAll('#compare-table thead th').length,11);
 assert.equal(w.document.querySelectorAll('#compare-table thead th')[3].style.borderTop,colour);
 assert.equal(w.document.querySelectorAll('#compare-charts svg').length,2);
 click('Drafted: Test Player 0');assert.match(w.document.querySelector('#compare-table').textContent,/Drafted/);
 w.document.querySelector('#compare-clear').click();assert.equal(w.document.querySelectorAll('#compare-table table').length,0);
 assert.equal(JSON.parse(w.localStorage.getItem('citrus-draft-desk:test')).rows[0].drafted,true);
 w.close();
});
test('shared chart normalization handles negative weights, disabled categories, missing data, and tied values',()=>{
 const dom=new JSDOM('<div id="charts"></div>',{runScripts:'outside-only'}),w=dom.window;
 w.eval(readFileSync(__dirname+'/../../packages/shared/src/draftCompare/charts.js','utf8'));
 const players=[{id:'1',name:'One',goalie:true,stats:{ga:100,saves:1000,wins:20}},{id:'2',name:'Two',goalie:true,stats:{ga:120,saves:1000,wins:30}},{id:'3',name:'Skater',goalie:false,stats:{goals:40}}];
 const stats=[{key:'ga',label:'Goals against',group:'goalie',weight:-3},{key:'saves',label:'Saves',group:'goalie',weight:.5},{key:'wins',label:'Wins',group:'goalie',weight:5},{key:'so',label:'Shutouts',group:'goalie',weight:2},{key:'goals',label:'Goals',group:'skater',weight:0}];
 const model=w.CitrusCompareCharts.models(players,stats,true).find(m=>m.goalie);
 assert.deepEqual(Array.from(model.impactDomain),[-360,500]);
 assert.ok(model.profiles[0].values[0]>model.profiles[1].values[0]);
 assert.equal(model.profiles[0].values[1],model.profiles[1].values[1]);
 assert.deepEqual(Array.from(w.CitrusCompareCharts.models(players,stats,false).find(m=>m.goalie).profiles[0].values),[0,50,0]);
 const weighted=w.CitrusCompareCharts.models(players,stats.map(s=>s.key==='wins'?{...s,weight:20}:s),true).find(m=>m.goalie);
 assert.ok(weighted.profiles[0].values[2]>model.profiles[0].values[2]);
 assert.equal(model.omitted,1);
 assert.equal(w.CitrusCompareCharts.models(players,stats,true).find(m=>!m.goalie).axes.length,0);
 assert.equal(new Set(w.CitrusCompareCharts.COLORS).size,10);
 const root=w.document.getElementById('charts');
 w.CitrusCompareCharts.render(root,{players,stats,impact:true});
 const first=root.querySelector('button');first.focus();first.click();
 assert.equal(w.document.activeElement.textContent,'1. One');
 assert.match(root.querySelector('[role="status"]').textContent,/Goals against -300 FPTS/);
 const axis=root.querySelector('select');axis.focus();axis.value='wins';axis.dispatchEvent(new w.Event('change'));
 assert.equal(w.document.activeElement.getAttribute('aria-label'),'Goalies X axis');
 dom.window.close();
});
