import { act, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { createLoadTiming, useLoadTiming } from '../useLoadTiming';
let frames: Map<number, FrameRequestCallback>;
let frameId: number;
const runFrame = () => { const pending = [...frames.values()]; frames.clear(); pending.forEach(callback => callback(0)); };
beforeEach(() => {
  vi.useFakeTimers(); vi.setSystemTime(1000); frames = new Map(); frameId = 0;
  vi.stubGlobal('requestAnimationFrame', (callback: FrameRequestCallback) => { frames.set(++frameId, callback); return frameId; });
  vi.stubGlobal('cancelAnimationFrame', (id: number) => frames.delete(id));
});
afterEach(() => { vi.unstubAllGlobals(); vi.useRealTimers(); });
const setup = () => {
  const timing = createLoadTiming();
  const node = document.createElement('div');
  timing.attach(node);
  timing.scope('private-league-a');
  return { timing, read: () => JSON.parse(node.dataset.loadTiming!) };
};
it('records epoch stages, exact-object commit and next frame separately from successful completion', () => {
  const { timing, read } = setup();
  timing.ready(true, true);
  const token = timing.begin('private-league-a');
  const roster = {};
  vi.setSystemTime(1200);
  timing.delivered(token, roster);
  timing.observe({}, false, true);
  expect(read().stages.firstLineupCommit).toBeUndefined();
  timing.observe(roster, true, true);
  expect(read().stages.dataCommit).toBe(1200);
  expect(read().stages.firstLineupCommit).toBeUndefined();
  vi.setSystemTime(1400);
  timing.mark(token, 'loadSettled');
  timing.observe(roster, false, true);
  expect(read().stages.usableDataComplete).toBe(1400);
  expect(read().stages.firstLineupCommit).toBe(1400);
  expect(read().stages.nextFrame).toBeUndefined();
  runFrame();
  expect(read().stages.nextFrame).toBeGreaterThanOrEqual(1400);
  expect(JSON.stringify(read())).not.toContain('private-league');
});
it('empty and failed loads never claim usable lineup even after loading releases', () => {
  const { timing, read } = setup();
  let token = timing.begin('private-league-a');
  const roster = {};
  timing.delivered(token, roster);
  timing.mark(token, 'loadSettled');
  timing.observe(roster, false, false);
  expect(read().stages.emptyCommit).toBe(1000);
  expect(read().stages.usableDataComplete).toBeUndefined();
  token = timing.begin('private-league-a');
  timing.mark(token, 'error');
  timing.delivered(token, roster);
  timing.mark(token, 'loadSettled');
  timing.observe(roster, false, true);
  expect(read().stages.firstLineupCommit).toBeUndefined();
  expect(read().stages.usableDataComplete).toBeUndefined();
});
it('discards obsolete scope, stale load markers and queued frame callbacks', () => {
  const { timing, read } = setup();
  const old = timing.begin('private-league-a');
  const roster = {};
  timing.delivered(old, roster);
  timing.observe(roster, false, true);
  timing.scope('private-league-b');
  expect(timing.begin('private-league-a')).toBe(-1);
  timing.mark(old, 'error');
  timing.delivered(old, roster);
  timing.observe(roster, false, true);
  runFrame();
  expect(read().stages).toEqual({ scopeStart: 1000 });
  const current = timing.begin('private-league-b');
  timing.begin('private-league-b');
  timing.mark(current, 'late');
  expect(read().stages.late).toBeUndefined();
  timing.dispose();
  timing.mark(current, 'afterUnmount');
  expect(read().stages.afterUnmount).toBeUndefined();
});
it('hook observes actual rendered identity and loading gate without extra renders', () => {
  const first = {};
  let renders = 0;
  const { result, rerender, unmount } = renderHook(({ scope, value, loading }) => {
    renders++;
    return useLoadTiming(scope, value, loading, true, true, true);
  }, { initialProps: { scope: 'a', value: first, loading: true } });
  const node = document.createElement('div');
  act(() => result.current.rootRef(node));
  const token = result.current.begin();
  const next = {};
  act(() => { result.current.timing.delivered(token, next); result.current.timing.mark(token, 'loadSettled'); });
  expect(renders).toBe(1);
  rerender({ scope: 'a', value: next, loading: false });
  expect(JSON.parse(node.dataset.loadTiming!).stages.firstLineupCommit).toBe(1000);
  rerender({ scope: 'b', value: next, loading: false });
  act(() => vi.advanceTimersByTime(30));
  expect(JSON.parse(node.dataset.loadTiming!).stages.nextFrame).toBeUndefined();
  unmount();
});

it('records background completion without demanding an extra React state update', () => {
  const { timing, read } = setup();
  const token = timing.begin('private-league-a');
  const roster = {};
  timing.delivered(token, roster);
  timing.observe(roster, false, true);
  expect(read().stages.firstLineupCommit).toBe(1000);
  expect(read().stages.usableDataComplete).toBeUndefined();
  vi.setSystemTime(1500);
  timing.mark(token, 'loadSettled');
  expect(read().stages.usableDataComplete).toBe(1500);
});
