-- ============================================================================
-- Fix remaining RLS gaps identified in comprehensive audit
-- 1. player_weekly_stats - missing RLS entirely
-- 2. fantasy_daily_rosters - overly permissive (all-authenticated for mutations)
-- 3. league_averages - overly broad mutation policy
-- ============================================================================

-- ─────────────────────────────────────────────────────────────
-- 1. player_weekly_stats: Enable RLS + public read policy
--    (Reference data generated by pipeline - read-only for clients)
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  EXECUTE 'ALTER TABLE public.player_weekly_stats ENABLE ROW LEVEL SECURITY';
EXCEPTION WHEN undefined_table THEN
  RAISE NOTICE 'Table player_weekly_stats does not exist, skipping';
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'player_weekly_stats') THEN
    -- Drop existing policies to avoid conflicts
    DROP POLICY IF EXISTS "Public can read player weekly stats" ON public.player_weekly_stats;
    DROP POLICY IF EXISTS "Service role can manage player weekly stats" ON public.player_weekly_stats;

    -- Public read access (reference data)
    CREATE POLICY "Public can read player weekly stats"
      ON public.player_weekly_stats FOR SELECT
      USING (true);

    -- Only service role can insert/update (pipeline writes)
    CREATE POLICY "Service role can manage player weekly stats"
      ON public.player_weekly_stats FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 2. fantasy_daily_rosters: Tighten mutation policies
--    Currently USING(true) for ALL operations - needs team ownership check
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'fantasy_daily_rosters') THEN
    -- Drop the overly permissive policies
    DROP POLICY IF EXISTS "Authenticated users can manage daily rosters" ON public.fantasy_daily_rosters;
    DROP POLICY IF EXISTS "Users can manage their own daily rosters" ON public.fantasy_daily_rosters;
    DROP POLICY IF EXISTS "Authenticated users can view all daily rosters" ON public.fantasy_daily_rosters;
    DROP POLICY IF EXISTS "Service role can manage daily rosters" ON public.fantasy_daily_rosters;

    -- Read: Anyone can view daily rosters (needed for matchup display)
    CREATE POLICY "Authenticated users can view all daily rosters"
      ON public.fantasy_daily_rosters FOR SELECT
      USING (true);

    -- Write: Only team owners can manage their own rosters
    CREATE POLICY "Users can manage their own daily rosters"
      ON public.fantasy_daily_rosters FOR INSERT
      WITH CHECK (
        EXISTS (
          SELECT 1 FROM public.teams t
          WHERE t.id = team_id AND t.owner_id = auth.uid()
        )
      );

    CREATE POLICY "Users can update their own daily rosters"
      ON public.fantasy_daily_rosters FOR UPDATE
      USING (
        EXISTS (
          SELECT 1 FROM public.teams t
          WHERE t.id = team_id AND t.owner_id = auth.uid()
        )
      );

    CREATE POLICY "Users can delete their own daily rosters"
      ON public.fantasy_daily_rosters FOR DELETE
      USING (
        EXISTS (
          SELECT 1 FROM public.teams t
          WHERE t.id = team_id AND t.owner_id = auth.uid()
        )
      );

    -- Service role bypass for pipeline operations
    CREATE POLICY "Service role can manage daily rosters"
      ON public.fantasy_daily_rosters FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 3. league_averages: Restrict mutations to service role only
--    (Pipeline-generated data, clients should only read)
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'league_averages') THEN
    -- Drop overly permissive authenticated policy
    DROP POLICY IF EXISTS "Authenticated users can manage league averages" ON public.league_averages;
    DROP POLICY IF EXISTS "Public can read league averages" ON public.league_averages;
    DROP POLICY IF EXISTS "Service role can manage league averages" ON public.league_averages;

    -- Public read access (reference data)
    CREATE POLICY "Public can read league averages"
      ON public.league_averages FOR SELECT
      USING (true);

    -- Only service role can mutate (pipeline writes)
    CREATE POLICY "Service role can manage league averages"
      ON public.league_averages FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- Verification
-- ─────────────────────────────────────────────────────────────
DO $$
DECLARE
  tbl TEXT;
  has_rls BOOLEAN;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY['player_weekly_stats', 'fantasy_daily_rosters', 'league_averages'])
  LOOP
    SELECT relrowsecurity INTO has_rls
    FROM pg_class
    WHERE relname = tbl AND relnamespace = 'public'::regnamespace;

    IF has_rls IS NULL THEN
      RAISE NOTICE 'Table % does not exist', tbl;
    ELSIF NOT has_rls THEN
      RAISE WARNING 'RLS NOT enabled on %', tbl;
    ELSE
      RAISE NOTICE 'RLS verified on %', tbl;
    END IF;
  END LOOP;
END $$;
