const VARIANTS = [
  {
    id: 'v1',
    label: 'V1: Brutalist Typography',
    vibe: 'Statsbomb × Linear × Bloomberg: the headline IS the design. Dense monospace data card. Tactical authority.',
    src: '/mockups/v1-brutalist.jpg',
  },
  {
    id: 'v2',
    label: 'V2: Editorial Elegance',
    vibe: 'The Athletic × Vercel × Apple: Playfair serif headline, refined initial-ring avatars, atmospheric warm glow.',
    src: '/mockups/v2-editorial.jpg',
  },
  {
    id: 'v3',
    label: 'V3: Moat-Forward',
    vibe: 'Linear × Stripe × OpenAI: sells the engine, not the players. The shot model out front. Zero licensing exposure.',
    src: '/mockups/v3-moat-forward.jpg',
  },
];

export default function PreviewMockups() {
  return (
    <div style={{ backgroundColor: '#08090C', color: '#E4E4E7', minHeight: '100vh', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '4rem 2rem' }}>
        <header style={{ marginBottom: '3rem', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '2rem' }}>
          <p style={{ fontSize: '11px', letterSpacing: '0.2em', textTransform: 'uppercase', color: '#71717A', marginBottom: '0.5rem' }}>
            Citrus · Homepage Redesign · Mockup Comparison
          </p>
          <h1 style={{ fontSize: '2.5rem', fontWeight: 700, letterSpacing: '-0.02em', marginBottom: '1rem', color: '#FFFFFF' }}>
            Three Directions
          </h1>
          <p style={{ fontSize: '1rem', lineHeight: 1.6, color: '#A1A1AA', maxWidth: '720px' }}>
            All three are license-clean (no player headshots, no team logos). Click any image to view at full resolution. Reply with which variant you want to ship. I'll rebuild the staging page to match.
          </p>
        </header>

        {VARIANTS.map((v) => (
          <section key={v.id} style={{ marginBottom: '5rem' }}>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: '1rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#FFFFFF', margin: 0 }}>{v.label}</h2>
              <a
                href={v.src}
                target="_blank"
                rel="noopener noreferrer"
                style={{ fontSize: '12px', letterSpacing: '0.15em', textTransform: 'uppercase', color: '#FF6B1A', textDecoration: 'none' }}
              >
                Open full-res →
              </a>
            </div>
            <p style={{ fontSize: '0.9375rem', lineHeight: 1.6, color: '#A1A1AA', marginBottom: '1.5rem', maxWidth: '720px' }}>
              {v.vibe}
            </p>
            <a href={v.src} target="_blank" rel="noopener noreferrer" style={{ display: 'block' }}>
              <img
                src={v.src}
                alt={v.label}
                style={{
                  width: '100%',
                  height: 'auto',
                  display: 'block',
                  border: '1px solid rgba(255,255,255,0.08)',
                  cursor: 'zoom-in',
                }}
                loading="lazy"
              />
            </a>
          </section>
        ))}

        <footer style={{ borderTop: '1px solid rgba(255,255,255,0.08)', paddingTop: '2rem', color: '#71717A', fontSize: '0.875rem' }}>
          Generated by Nano Banana (Gemini 3.1 Flash Image). Reply in chat with V1, V2, V3, or a hybrid spec.
        </footer>
      </div>
    </div>
  );
}
